_wandb:
    value:
        cli_version: 0.21.3
        e:
            8s368ji4a8890312o6nixuxmw2o42wpz:
                codePath: waste_segregation\main.ipynb
                codePathLocal: main.ipynb
                cpu_count: 24
                cpu_count_logical: 24
                cudaVersion: "13.0"
                disk:
                    /:
                        total: "999331721216"
                        used: "201028345856"
                email: diptosen2017@gmail.com
                executable: d:\SEM 7\CVProject\.venv\Scripts\python.exe
                git:
                    commit: b37f57bf0a790a6c293c5da59231da572acd2e98
                    remote: https://github.com/dipto8103/waste_segregation.git
                gpu: NVIDIA GeForce RTX 5070 Ti Laptop GPU
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Blackwell
                      cudaCores: 5888
                      memoryTotal: "12820938752"
                      name: NVIDIA GeForce RTX 5070 Ti Laptop GPU
                      uuid: GPU-f6a7b0c5-e6bf-1955-1895-7fd04dd38778
                host: DIPTO-LAPTOP-PRO
                memory:
                    total: "68033028096"
                os: Windows-10-10.0.26100-SP0
                program: d:\SEM 7\CVProject\waste_segregation\main.ipynb
                python: CPython 3.10.7
                root: d:\SEM 7\CVProject\waste_segregation
                startedAt: "2025-09-07T22:14:59.210235Z"
                writerId: 8s368ji4a8890312o6nixuxmw2o42wpz
        m: []
        python_version: 3.10.7
        t:
            "1":
                - 5
                - 53
            "2":
                - 5
                - 53
            "3":
                - 2
                - 13
                - 16
            "4": 3.10.7
            "5": 0.21.3
            "8":
                - 1
                - 3
            "10":
                - 20
            "12": 0.21.3
            "13": windows-amd64
        visualize:
            val_confusion_matrix:
                panel_config:
                    fieldSettings:
                        Actual: Actual
                        Predicted: Predicted
                        nPredictions: nPredictions
                    panelDefId: wandb/confusion_matrix/v1
                    stringSettings:
                        title: Confusion Matrix Curve
                    transform:
                        name: tableWithLeafColNames
                    userQuery:
                        queryFields:
                            - args:
                                - name: runSets
                                  value: ${runSets}
                              fields:
                                - fields: []
                                  name: id
                                - fields: []
                                  name: name
                                - fields: []
                                  name: _defaultColorIndex
                                - args:
                                    - name: tableKey
                                      value: val_confusion_matrix_table
                                  fields: []
                                  name: summaryTable
                              name: runSets
                panel_type: Vega2
class_weight:
    value: balanced_subsample
features:
    value:
        - BoVW512
        - HOG~34600
        - HSV51
max_depth:
    value: null
model:
    value: RandomForest
n_estimators:
    value: 500
scaler:
    value: StandardScaler(with_mean=False)
